services:
  db:
    image: postgres:latest
    container_name: spring-container
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: db-spring
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: